name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        cxx: [clang++, g++]
        cxx_version: [11, 20]

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install boost
      run: |
        sudo apt-get update
        sudo apt-get install libboost-dev

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_CXX_COMPILER=${{matrix.cxx}}
        -DCMAKE_CXX_STANDARD=${{matrix.cxx_version}}
        -DCMAKE_CXX_FLAGS="-Werror"

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      # Speed.* are disabled because some of them are right on the edge, and it
      # depends on system load besides.
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -E Speed

  build-windows:
    strategy:
      matrix:
        platform: [Win32, x64]
        cxx_version: [11, 23]

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      # The /EHsc /GR flags are ~ the default value of CMAKE_CXX_FLAGS.
      # https://gitlab.kitware.com/cmake/cmake/-/issues/20610
      run: >
        cmake -B ${{github.workspace}}/build
        -A ${{matrix.platform}}
        -DCMAKE_CXX_STANDARD=${{matrix.cxx_version}}
        -DCMAKE_CXX_FLAGS="/WX /GR /EHsc"
        -Dgtest_force_shared_crt=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Speed.* are disabled because some of them are right on the edge, and it
      # depends on system load besides.
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -E Speed
