name: Generate & deploy documentation

on:
  push:
    branches:
      - feature/doc-generation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run DenverCode1/doxygen-github-pages-action
        working-directory: docs
        uses: DenverCoder1/doxygen-github-pages-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
